import type { NextPage } from "next";
import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { ImageLoader } from "three";
import styles from "../styles/Home.module.css";
import { useEffect, useRef } from "react";

function MeshGeneration(props: any) {
  const geo = useRef(null);
  useEffect(() => {
    function createHeightMap(image: HTMLImageElement) {
      const w = image.width;
      const h = image.height;
      const canvas = document.getElementById("useLessCanvas") as HTMLCanvasElement;
      const ctx = canvas.getContext("2d") as CanvasRenderingContext2D;
      ctx.drawImage(image, 0, 0);
      const data = ctx.getImageData(0, 0, w, h);
      console.log(data.data);
    }
    const image = new ImageLoader();
    image.load("/h64.png", createHeightMap);
  }, []);
  return (
    <mesh {...props}>
      <bufferGeometry ref={geo} />
    </mesh>
  );
}

//function Planate(props: any) {
//  return (
//    <mesh
//      {...props}
//      scale={1}
//      onClick={(e: any) => {
//        console.log(e);
//      }}
//    >
//      <sphereGeometry args={[1]} />
//      <meshStandardMaterial color={"hotpink"} />
//    </mesh>
//  );
//}

const Home: NextPage = () => {
  const extraCanvas = useRef(null);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.full}>
        {/* 
        useLessCanvas has only one task => get the image data
      */}
        <canvas
          id="useLessCanvas"
          ref={extraCanvas}
          style={{ display: "none" }}
        ></canvas>
        <Canvas>
          <ambientLight />
          <pointLight />
          <MeshGeneration />
        </Canvas>
      </main>
    </div>
  );
};

export default Home;
